### PR TITLE
Fabric 1.19.1 and 1.19.2

### PR DESCRIPTION
**Pull request by igoticecream**
Adds support for ~1.91.1 (post chat reporting feature, which changes the way messages are sent)
Adds support for Allay, Frogs and Warden mob entities

### CODE REVIEW

**Comment by igoticecream** [comment]
Target branch is 1.18 ( so you can review the changes), I can't create a branch for 1.19 in your repository

**Comment by vacla** [comment]
I'm holding off for merging this pr due to me maybe updating it very soon with the malilib rewrite branch

**Comment by 4rm4g3dd0n** [comment]
Is the project abandoned or?

**Comment by vacla** [comment]
It is not abandoned, due to personal reasons i had to take a bit time off, i will be starting to slowly update to each version very soon

**Comment by vacla** [comment]
Closing as release has been published for 1.19.1 and 1.19.2

**Pull request closed without merging**
